### ISSUE TITLE
WPA: My bookings calendar selection

### ISSUE THREAD

**Issue by stakach** [PlaceOS/user-interfaces#171]
Sorry if this is a duplicate, this is from the discussion we had with @MrYuion and @jeremyw24 
<img width="319" alt="image" src="https://user-images.githubusercontent.com/368013/179989795-7a37867d-4ed1-4b19-960a-442c4f80ef72.png">

I can't actually see the frontend making a request to get the list of calendars that the user can view
I tested staff-api: https://placeos-dev.aca.im/api/staff/v1/calendars
which returns
```yaml
[
    {
        "id": "IsaiahL@l6yy.onmicrosoft.com",
        "ref": "AAkALgAAAAAAHYQDEapmEc2byACqAC-EWg0Az6dqyGmu3kOBLHhUlRzl5gAAAADjBQAA",
        "summary": "Calendar",
        "primary": true,
        "can_edit": true
    },
    { # this is the delegated calendar
        "id": "placeosazuresandbox@l6yy.onmicrosoft.com",
        "ref": "AAkALgAAAAAAHYQDEapmEc2byACqAC-EWg0Az6dqyGmu3kOBLHhUlRzl5gAAT-zWtwAA",
        "summary": "FNU LNU",
        "primary": false,
        "can_edit": true
    }
]
```

I'm not 100% sure the API is returning all delegated calendars, just ones that are moved into the "my calendars" group
but this is a good start

Then to list the bookings for a `non-primary` calendar, use:
https://placeos-dev.aca.im/api/staff/v1/events?calendars=placeosazuresandbox@l6yy.onmicrosoft.com&period_start=1655647200&period_end=1658239200

there is the `can_edit` flag too which is worth taking note of, in terms of actions allowed on the events
